
("FTP.DGO"
;;("jungleb-vis.go")
("static-screen.o" "forbidden-temple.go")
("tpage-1513.go" "tpage-1513")
("forbidden-temple.go" "forbidden_temple")
("mistycannon.ag.go" "mistycannon")
("mistycannon.o" "mistycannon")
("plat-ag.o" "plat")
("plat-ag.go" "plat")
("plat-jungleb-ag.go" "plat-jungleb")
("plat-flip.o" "plat-flip")
("plat-flip-ag.go" "plat-flip")
("tpage-485.go")
("tpage-510.go")
("tpage-507.go")
("tpage-966.go")
)